/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_JniTest */

#ifndef _Included_com_example_test_JniTest
#define _Included_com_example_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_JniTest
 * Method:    helloworld_fromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_JniTest_helloworldFromC
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_test_JniTest_add
        (JNIEnv *, jobject, jint, jint);

JNIEXPORT jstring JNICALL Java_com_example_test_JniTest_sayHelloInC
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
